Algoritmo "Olá mundo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Escreve e lê algo
// Autor(a)    : Giovanna Cavalcante
// Data atual  : 29/03/2022
Var
// Seção de Declarações das variáveis 



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval ("Olá, mundo. Este é o curso de Inteligência Artificial!")
Fimalgoritmo
